name: Normalize composer.json

on:
    push:
        paths:
            - "composer.json"

jobs:
    normalize:
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v2

            - name: Run composer normalize
              uses: docker://ergebnis/composer-normalize-action:latest

            - uses: stefanzweifel/git-auto-commit-action@v4.0.0
              with:
                  commit_message: normalize composer.json
